### ISSUE TITLE
Update site design

### ISSUE THREAD

**Issue by RandomlyKnighted** [ligershark/SideWaffleWebsite#12]
Recently we've been doing a lot of work in adding new templates, updating existing ones, and adding new features like the dynamic updates feature. I feel like the one page site we have now for SideWaffle is going to be getting a bit long and can be overwhelming at times to go through. In order to keep the content clearer and more to the point what are your thoughts on updating the site design? I'd love to add a page dedicated to the change log similar to the one on the Web Essentials website, where you can select the version and only view the changes for that version.

**Comment by RandomlyKnighted** [comment]
@madskristensen @sayedihashimi what are you thoughts on this?

**Comment by sayedihashimi** [comment]
Sounds good to me, @madskristensen what do you think?

**Comment by madskristensen** [comment]
:+1:

**Comment by RandomlyKnighted** [comment]
@madskristensen @sayedihashimi would either of you be against me changing the site over to ASP.NET 5? I'd like to get more experience with it and I think this would be a good way to do that.

By the way, where is the site hosted?

**Comment by madskristensen** [comment]
Makes sense. Sayed is hosting it

**Comment by sayedihashimi** [comment]
We should work on that in a different branch.

**Comment by RandomlyKnighted** [comment]
The design is slowly getting there. I just ran into some minor issues with using partials in ASP.NET 5. I hope to have something to show you both soon.

By the way, do we have a Privacy Policy or Terms of Use that I can add to the website? I'm assuming that since the extension is a product that we'd have something like this available if anyone ever asked for it.

**Comment by sayedihashimi** [comment]
We don't have anything like that. To my knowledge no one has asked for it.

**Comment by RandomlyKnighted** [comment]
Ok, what about when I list the team members? I've got all the ones that was on the previous design. Do I add Kent or any other contributors as well? How do we decide who's names go on the site going forward? I've got you and @madskristensen listed as Co-Founders. Everyone else is just listed as contributors. Is that accurate since there are contributions besides just templates?

**Comment by RandomlyKnighted** [comment]
Seeing as we now have a `next` branch with the new design I'm going to go ahead and close this.
