### ISSUE TITLE
Hosting a Nightly build

### ISSUE THREAD

**Issue by RandomlyKnighted** [ligershark/SideWaffleWebsite#15]
When getting feedback from people Sayed and I have at times provided links to the Appveyor artifacts .vsix file so people can test a new feature. To make this easier, what are your thoughts on hosting a nightly SideWaffle build via our website? I know we don't have PRs or merges quite as often as WebEssentials, but I feel like this could be very useful especially now that we are including Google Analytics in SideWaffle. Mainly, because we will be able to better to focus on templates that people use the most. I was thinking that it could just be a VSIX that's generated when a merge is completed into the master branch. That way as soon as a merge, anyone who wants to test it can immediately download it and can begin testing.

cc: @sayedihashimi @madskristensen

**Comment by madskristensen** [comment]
The nightly build is right here http://vsixgallery.com/extension/e6e2a48e-387d-4af2-9072-86a5276da6d4/

**Comment by sayedihashimi** [comment]
Every build gets published to http://vsixgallery.com/extension/e6e2a48e-387d-4af2-9072-86a5276da6d4/. Usually that's the latest version in main. During a `release` it can be the version from the publish branch though. We could condition that to not happen from the `release` branch though so that we always have it.

**Comment by RandomlyKnighted** [comment]
Cool, I wasn't aware that the Open VSIX Gallery was our nightly build. Alright, once we get the new site design up. Are both of you ok with me adding a download to the Nightly build?

@sayedihashimi What if we made Open VSIX Gallery just be the master branch and had the Visual Studio Gallery pull from the release branch?

**Comment by sayedihashimi** [comment]
@RandomlyKnighted works for me. We just have to add an if statement around https://github.com/ligershark/side-waffle/blob/master/appveyor.ps1#L16

**Comment by RandomlyKnighted** [comment]
I'm started working on adding the nightly build to the website last night. I've also went ahead and created an issue regarding fixing it so that the nightly build only pulls from the master branch.
