### ISSUE TITLE
custom wizard

### ISSUE THREAD

**Issue by alhardy** [ligershark/SideWaffleWebsite#9]
Thanks for the great project!
Ive been looking at custom project wizards, it looks like you've fiddle with these but don't have any samples. Have you come across a way to access the wizard without install the containing assembly in the gac?

**Comment by sayedihashimi** [comment]
There is some info on the wiki at https://github.com/ligershark/side-waffle/wiki/How-to-use-a-custom-wizard. I'll close this now but if you need more info feel free to reopen.
